# Generated by Django 3.2.5 on 2021-07-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortenre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url_strings',
            name='url_title',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
