# Generated by Django 3.2.5 on 2021-07-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortenre', '0002_url_strings_url_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_strings',
            name='url_title',
            field=models.CharField(default='random', max_length=20),
        ),
    ]
