# Generated by Django 3.2.5 on 2021-07-05 06:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortenre', '0003_alter_url_strings_url_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='url_strings',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 6, 37, 39, 496524, tzinfo=utc), verbose_name='date published'),
        ),
    ]
